package com.learning.englishpro.ai.service;

import com.learning.englishpro.ai.dto.GeminiRequest;
import com.learning.englishpro.ai.dto.GeminiResponse;
import com.learning.englishpro.common.exception.AppException;
import com.learning.englishpro.common.exception.ErrorCode;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Service;
import org.springframework.web.client.HttpServerErrorException;
import org.springframework.web.client.RestClientException;
import org.springframework.web.client.RestTemplate;

import java.util.List;

@Service
@Slf4j
public class AiService {

    @Value("${ai.gemini.url}")
    private String geminiUrl;

    @Value("${ai.gemini.api-key}")
    private String geminiApiKey;

    @Value("${ai.gemini.max-retries:3}")
    private int maxRetries;

    @Value("${ai.gemini.retry-delay-ms:2000}")
    private long retryDelayMs;

    private final RestTemplate restTemplate;

    public AiService() {
        this.restTemplate = new RestTemplate();
    }

    /**
     * Call Gemini API and return the raw JSON string generated by the AI
     */
    public String generateJson(String systemPrompt, String userPrompt, Double temperature) {
        if (temperature == null) {
            temperature = 0.3;
        }
        GeminiRequest requestBody = GeminiRequest.of(systemPrompt, userPrompt, temperature);
        return callGeminiWithRetry(requestBody, "generateJson");
    }

    public String generateChat(String systemPrompt, List<GeminiRequest.Content> contents, Double temperature) {
        if (temperature == null) {
            temperature = 0.7;
        }
        GeminiRequest requestBody = GeminiRequest.ofChat(systemPrompt, contents, temperature);
        return callGeminiWithRetry(requestBody, "generateChat");
    }

    /**
     * Calls Gemini API with automatic retry on 503 (Service Unavailable) errors.
     */
    private String callGeminiWithRetry(GeminiRequest requestBody, String context) {
        String fullUrl = geminiUrl + geminiApiKey;

        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        HttpEntity<GeminiRequest> entity = new HttpEntity<>(requestBody, headers);

        int attempt = 0;
        while (attempt <= maxRetries) {
            try {
                if (attempt > 0) {
                    log.warn("[{}] Retry attempt {}/{} after {}ms...", context, attempt, maxRetries, retryDelayMs);
                    Thread.sleep(retryDelayMs * attempt); // exponential-ish backoff
                }

                log.info("[{}] Sending request to Gemini API (attempt {})...", context, attempt + 1);
                GeminiResponse response = restTemplate.postForObject(fullUrl, entity, GeminiResponse.class);

                if (response != null) {
                    String extractedText = response.extractText();
                    log.info("[{}] Received response from AI successfully.", context);
                    return extractedText;
                } else {
                    throw new AppException(ErrorCode.INTERNAL_SERVER_ERROR);
                }

            } catch (HttpServerErrorException.ServiceUnavailable e) {
                // 503: Model overloaded - retry
                log.warn("[{}] Gemini API returned 503 (Service Unavailable). attempt={}/{}", context, attempt + 1, maxRetries + 1);
                attempt++;
                if (attempt > maxRetries) {
                    log.error("[{}] All {} retry attempts failed. Giving up.", context, maxRetries + 1);
                    throw new RuntimeException("Gemini AI hiện đang quá tải. Vui lòng thử lại sau ít phút.", e);
                }
            } catch (InterruptedException ie) {
                Thread.currentThread().interrupt();
                throw new RuntimeException("Request interrupted during retry wait.", ie);
            } catch (RestClientException e) {
                log.error("[{}] Error communicating with AI API: ", context, e);
                throw new RuntimeException("Failed to call AI API", e);
            }
        }

        throw new RuntimeException("Unexpected state in callGeminiWithRetry");
    }
}
